const options = {
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'PTIT Exam API',
        version: '1.0.0',
        description: 'PTIT Exam API with autogenerated swagger doc',
      },
      servers:[
        {url:'http://localhost:8080'},
        {url:'https://web-tn-backend.onrender.com'},
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT'
          }
        }
      },
      security: [
        {
          bearerAuth: []
        }
      ],
    },
  
    apis: ['./routes/*.js'],
};

function getOptions() {
    return options;
}

module.exports = getOptions;